version: '3.8'

volumes:
  qgis-settings:
services:
  qgis:
    build: . 
    user: "${UID_GID}"
    extra_hosts: &extra_hosts
      - hostmachine:172.17.0.1
    volumes:
      - /home/$USER:/app
      - /opt/kart:/app/kart
      - /tmp/.X11-unix:/tmp/.X11-unix
      - qgis-settings:/home/user/.local/share/QGIS/QGIS3/profiles/default
      - /home/$USER.local/share/QGIS/:/home/user/.local/share/QGIS:rw
      - /home/$USER/.pg_service.conf:/tmp/.pg_service.conf:rw
    environment:
      - PGSERVICEFILE=/tmp/.pg_service.conf
      - PYTHONPATH=/app:/usr/share/qgis/python/plugins/
      - QGIS_DEBUG=3
      - QGIS_LOG_FILE=/dev/null
      - QGIS_PLUGINPATH=/app
      - XDG_RUNTIME_DIR=/tmp/runtime-$USER
      - DISPLAY=$DISPLAY    
    entrypoint: ""
    command: qgis 
